{{- if .Values.elasticsearch.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
        env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: {{ .Values.elasticsearch.env.javaOpts }}
        - name: xpack.security.enabled
          value: {{ .Values.elasticsearch.env.xpackSecurityEnabled }}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        resources:
          {{- toYaml .Values.elasticsearch.resources | nindent 10 }}
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  {{- if .Values.elasticsearch.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.elasticsearch.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging
spec:
  selector:
    app: elasticsearch
  ports:
  - port: {{ .Values.elasticsearch.service.httpPort }}
    targetPort: 9200
    name: http
  - port: {{ .Values.elasticsearch.service.transportPort }}
    targetPort: 9300
    name: transport
  type: {{ .Values.elasticsearch.service.type }}
{{- end }}