apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: blogzy
type: Opaque
data:
  secret-key: ZGV2LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=  # dev-secret-key-change-in-production
  jwt-secret-key: and0LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=  # jwt-secret-key-change-in-production