{{- if .Values.global.aws.rds.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  rds-user: {{ .Values.secrets.rds.user | b64enc }}
  rds-password: {{ .Values.secrets.rds.password | b64enc }}
  rds-endpoint: {{ .Values.secrets.rds.endpoint | b64enc }}
{{- end }}