apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  postgres-user: {{ .Values.secrets.postgres.user | b64enc }}
  postgres-password: {{ .Values.secrets.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.backend.secretKey | b64enc }}
  jwt-secret-key: {{ .Values.secrets.backend.jwtSecretKey | b64enc }}