apiVersion: v2
name: logging
description: A Helm chart for Blogzy logging with EFK stack
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Blogzy Team
    email: team@blogzy.example.com